In [1]:
import numpy as np
import scipy
from scipy.linalg import fractional_matrix_power as fracpow
from numpy.linalg import matrix_power as matpow
from numpy.linalg import eig as eigvv
np.set_printoptions(threshold=np.nan)

# Simple Connected Graph

A simple connected undirected graph with $n=|V|=4$ vertices.

<br><br>

![simple_graph](images/simple_graph.png)

<br><br>

Thus indices $i \in [0,n-1]$.

<br>

The adjacency matrix $A$ defines the connectivity of the graph:
$$
A_{ij} = 
\begin{cases}
2 & \text{ if loop at } i=j \\
1 & \text{ if edge from vertex i to j} \\
0 & \text{ otherwise}
\end{cases}
$$

<br>

The degree matrix $D$ is diagonal, giving the number of edges at each node:
$$
D_{ii} = \sum_j A_{ij}
$$

<br>

The distance matrix $d$ gives the shortest path from node $i \rightarrow j$

$$
d_{ij} = 
\begin{cases}
\text{number of edges defining shortest path from } i \rightarrow j\\
0 \text{ on diagonal}
\end{cases}
$$

In [2]:
# Adjacency matrix A for example
A = np.zeros((4, 4))
A[1,0] = 1
A[2,1] = 1
A[3,1] = 1
A[3,2] = 1
A += A.T
print('Adjacency Matrix A:')
print(A)

Adjacency Matrix A:
[[0. 1. 0. 0.]
 [1. 0. 1. 1.]
 [0. 1. 0. 1.]
 [0. 1. 1. 0.]]


In [3]:
# Degree matrix D for example
D = np.zeros(A.shape)
for i in range(0,A.shape[0]):
    D[i,i] = A[:,i].sum()
print('Degree Matrix D:')
print(D)

Degree Matrix D:
[[1. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


In [4]:
# Value (A^n)ij gives maximum number of walks (paths) of length n between vertices i & j
A2 = matpow(A,2)
A3 = matpow(A,3)
A10 = matpow(A,10)
print('A x A:')
print(A2)
print('A x A x A:')
print(A3)
print('A^10')
print(A10)

A x A:
[[1. 0. 1. 1.]
 [0. 3. 1. 1.]
 [1. 1. 2. 1.]
 [1. 1. 1. 2.]]
A x A x A:
[[0. 3. 1. 1.]
 [3. 2. 4. 4.]
 [1. 4. 2. 3.]
 [1. 4. 3. 2.]]
A^10
[[197. 380. 349. 349.]
 [380. 895. 729. 729.]
 [349. 729. 638. 637.]
 [349. 729. 637. 638.]]


# Laplacian

For simple graph, the Laplacian is given by $L = D - A$,

$$
L_{ij} =
\begin{cases}
 \text{deg} \,  v_i & \text{ if } i=j \\
 -1 & \text{ if } i \neq j \text{ and } v_i \text{ adjacent to } v_j \\
 0 & \text{ otherwise}
\end{cases}
$$

<br>

The symmetric, normalized Laplacian $L_{\text{norm}}$ is given by

$$
L_{\text{norm}} = D^{-1/2} \, L \, D^{-1/2} = I - D^{-1/2} \, A \, D^{-1/2} \, ,
$$

$$
L^{\text{norm}}_{ij} =
\begin{cases}
 1  &\text{ if } i=j  \text{ and deg} \, v_i \neq 0 \\
 -\left( \text{deg } v_i \, \text{deg } v_j \right)^{-1/2} & \text{ if } i \neq j \text{ and } v_i \text{ adjacent to } v_j \\
 0 & \text{ otherwise}
\end{cases}
$$

<br>
The resulting spectrum of eigenvalues are all non-negative real values: $\lambda^{\text{norm}}_i \in \mathbb{R}_{\geq 0} \ \ , \ \forall i$

In [5]:
# Laplacian & normalized Laplacian
L = D-A

D_h = fracpow(D,-0.5)
L_norm = np.matmul(D_h, np.matmul(A, D_h))

print('Laplacian')
print(L)

print('\n')

print('L_norm')
print(L_norm)

Laplacian
[[ 1. -1.  0.  0.]
 [-1.  3. -1. -1.]
 [ 0. -1.  2. -1.]
 [ 0. -1. -1.  2.]]


L_norm
[[0.         0.57735027 0.         0.        ]
 [0.57735027 0.         0.40824829 0.40824829]
 [0.         0.40824829 0.         0.5       ]
 [0.         0.40824829 0.5        0.        ]]


In [6]:
# Eigenvalues and eigenvectors of L, L_norm
lam_L, vec_L = eigvv(L)
print('Eigenvalues, vectors of L')
print(lam_L)
print(vec_L)

print('\n')

lam_norm_L, vec_norm_L = eigvv(L_norm)
print('Eigenvalues, vectors of L_norm')
print(lam_norm_L)
print(vec_norm_L)

Eigenvalues, vectors of L
[ 4.00000000e+00  1.00000000e+00 -1.51136928e-16  3.00000000e+00]
[[-2.88675135e-01 -8.16496581e-01 -5.00000000e-01 -1.11437188e-16]
 [ 8.66025404e-01  1.46343894e-16 -5.00000000e-01  2.22874376e-16]
 [-2.88675135e-01  4.08248290e-01 -5.00000000e-01 -7.07106781e-01]
 [-2.88675135e-01  4.08248290e-01 -5.00000000e-01  7.07106781e-01]]


Eigenvalues, vectors of L_norm
[-0.72871355  0.22871355  1.         -0.5       ]
[[ 5.82736062e-01  7.31723091e-01 -3.53553391e-01 -6.61852455e-17]
 [-7.35511335e-01  2.89867343e-01 -6.12372436e-01  5.73181040e-17]
 [ 2.44378557e-01 -4.36209951e-01 -5.00000000e-01 -7.07106781e-01]
 [ 2.44378557e-01 -4.36209951e-01 -5.00000000e-01  7.07106781e-01]]
